# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-17 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[(b'file', b'file'), (b'server', b'server')], default=b'file', max_length=50),
        ),
    ]
