# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='key',
            field=models.CharField(default='/', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='path',
            field=models.CharField(default='/', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('file', 'file'), ('server', 'server')], default='file', max_length=50),
        ),
    ]
