# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_auto_20160919_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='key',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
